name: flutter_widget
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2

flutter:

  uses-material-design: true

# flutter_launcher_icons 설정값 변경 후 컴파일 명령어 입력
# 아래는 컴파일 명령
# flutter pub run flutter_launcher_icons:main
flutter_icons:
  image_path: "assets/launcher/ic-launcher-readytofly.png"
  android: true
  ios: true

# flutter_native_splash 설정값 변경 후 컴파일 명령어 입력
# 아래는 컴파일 명령
# flutter pub run flutter_native_splash:create 생성
# flutter pub run flutter_native_splash:remove 삭제
flutter_native_splash:
  image: "assets/images/img-splash-drone.png" # 중앙 로고 이미지
  color: "#197AEA" # 배경색
  branding: "assets/images/img-logo-smatii-mi_1.png" # 하단 브랜딩 이미지
  android_12:
    image: "assets/images/img-splash-drone.png" # 중앙 로고 이미지
    color: "#197AEA" # 배경색
    branding: "assets/images/img-logo-smatii-mi_1.png" # 하단 브랜딩 이미지
  # fullscreen: true # 안드로이드 12미만 브랜딩 이미지 가려지는 이슈로 주석처리
  android: true
  ios: true
