name: flutter_widget # (1) 앱의 이름
description: A new Flutter project. # (2) 앱에 대한 간단한 설명
version: 1.0.0+1 # (3) 앱의 버전 번호

environment:
  sdk: '>=3.1.0 <4.0.0' # (4) Flutter SDK의 지원 버전 범위

dependencies:
  flutter:
    sdk: flutter # (5) Flutter SDK 의존성
  cupertino_icons: ^1.0.2 # (6) 외부 패키지 의존성

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # (7) 내부 패키지 의존성

flutter:
  uses-material-design: true

  assets:
    - assets/ # 앱에 포함될 정적 자원 디렉토리 (이미지 등)
    - assets/fonts  
    - assets/images  

  fonts:
    - family: Pretendard  # 폰트 패밀리 이름
      fonts:
        - asset: assets/fonts/pretendard/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/pretendard/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/pretendard/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/pretendard/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/pretendard/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/pretendard/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/pretendard/Pretendard-Black.otf
          weight: 900