import 'package:flutter/material.dart';

class IconExample extends StatelessWidget {
  const IconExample({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('IconExample')),
      body: const Column(
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceAround,
            children: <Widget>[
              Icon(
                Icons.favorite,
                color: Colors.pink,
                size: 24.0,
                semanticLabel: 'Text to announce in accessibility modes',
              ),
              Icon(
                Icons.audiotrack,
                color: Colors.green,
                size: 30.0,
              ),
              Icon(
                Icons.beach_access,
                color: Colors.blue,
                size: 36.0,
              ),
            ],
          ),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceAround,
            children: <Widget>[
              Icon(
                MyIcons.dollar,
                color: Colors.pink,
                size: 24.0,
                semanticLabel: 'Text to announce in accessibility modes',
              ),
              Icon(
                MyIcons.percent,
                color: Colors.green,
                size: 30.0,
              ),
              Icon(
                MyIcons.ampersand,
                color: Colors.blue,
                size: 36.0,
              ),
            ],
          ),
        ],
      ),
    );
  }
}

/// Flutter icons DUIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DUIcons
///      fonts:
///       - asset: fonts/DUIcons.ttf
///
///
///

class MyIcons {
  MyIcons._();

  static const _kFontFam = 'SocialMediaIcons';
  static const String? _kFontPkg = null;

  static const IconData dollar = IconData(0x24, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData percent = IconData(0x25, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ampersand = IconData(0x26, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
