include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  exclude: [
      lib/**.g.dart,
    ] #예외처리

linter:
  rules:
    avoid_print: false
    depend_on_referenced_packages: false
    unnecessary_this: false
