name: flutter_application_18
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.6
  responsive_framework: ^1.5.1
  google_fonts: ^6.2.1
  animations: ^2.0.11
  loading_gifs: ^0.3.0
  url_launcher: ^6.3.0
  go_router: ^14.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

# flutter pub run flutter_launcher_icons
flutter_icons:
  image_path: "assets/Minimal-Logo.png"
  web:
    generate: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
